### PR TITLE
add default type for user-land types

### PR DESCRIPTION
**Pull request by LumaKernel**
align with `BaseSource/BaseFilter`

### CODE REVIEW

**Comment by Shougo** [comment]
Please describe after it merged.
The source implementation will be easy?

**Comment by LumaKernel** [comment]
For users who use `class MySource extends BaseSource {` (no param). They are needed to write `OnEventArguments<Record<string, unknown>>`. Users can use `OnEventArguments` (without type param) instead after merged. Removing asymmetricity.

It's good alternative to remove default `Param` from `BaseSource`/`BaseFilter` because user should be interested in `Param` because `param() { ... }` implementation is now required.

**Comment by LumaKernel** [comment]
The current users who is not so familiar with TS can easily update to this version.

**Comment by Shougo** [comment]
Param is required.
So the default Param should be removed?

Please describe cons and pros with examples.
I need to decide the choices.

**Comment by LumaKernel** [comment]
Okay, thanks.

Asymmetric of `BaseSource`/`BaseFilter` vs `...Arguments` about `Param` necessity is wrongly shipped by my PR (https://github.com/Shougo/ddc.vim/pull/53).

## 1st option: no change

```ts
class MySource extends BaseSource {
  // {} is needed
  async gatherCandidates(args: GatherCandidatesArguments<{}>) {
    // ...
    return [];
  }
  params() { return {} }
}
```

## 2nd option (this PR):

```ts
class MySource extends BaseSource {
  // {} is not needed
  async gatherCandidates(args: GatherCandidatesArguments) {
    // ...
    return [];
  }
  params() { return {} }
}
```

## 3rd option (Param is required for BaseSource/BaseFilter):

```ts
// {} is necessary here too
class MySource extends BaseSource<{}> {
  gatherCandidates(args: GatherCandidatesArguments<{}>) {
    // ...
    return [];
  }
  params() { return {} }
}
```

**Comment by Shougo** [comment]
> 3rd option (Param is required for BaseSource/BaseFilter):

I think it is better.

**Comment by Shougo** [comment]
Please fix CI errors.

**Comment by Shougo** [comment]
OK. Merged.

**Pull request merged**
