### PR TITLE
[WIP] Use `ReadableStream` as an interface of source

### PR DESCRIPTION
**Pull request by Shougo**
The continue of #14

### CODE REVIEW

**Comment by Shougo** [comment]
Problems:

* Cannot sort candidates properly (same with `maxCandidates`)
* Cannot merge `completePos` and `candidates`.

**Comment by Shougo** [comment]
@lambdalisue Can you fix the problems?
Your implementation is efficient, but it breaks some features.

**Comment by lambdalisue** [comment]
I'll check it this weekend (if you can wait.) To make things clear, please apply lint fixes or whatever is not related to the changes on this PR independently first (e.g https://github.com/Shougo/ddc.vim/pull/15/commits/0e3d48dda29e6b1eaa4325e28fb134d70889b2b5, https://github.com/Shougo/ddc.vim/pull/15/commits/29972defff2a14607f6104bc91291a0b94330b96)

**Comment by lambdalisue** [comment]
I'll re-consider the implementations this weekend but I think I would drop this PR and make a new one with some improvements to the original implementations instead.

I suggested you use `ReadableStream` because I thought you'd like to support gradual candidate updates in the future but you said it's not necessary at vim-jp Slack so probably using `ReadableStream` here is not the best approach while it introduces unnecessary complexity. The original `Promise<Candidate[]>` or similar seems enough for that purpose.

**Comment by lambdalisue** [comment]
I think this should be closed.

**Comment by Shougo** [comment]
Yes.  I have closed.

**Pull request closed without merging**
